<a href="https://colab.research.google.com/github/Vithya-Sree/Python_Libraries-/blob/main/Numpy%26Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

1. Create a 1D NumPy Array

In [ ]:
temperatures_w1 = np.array([22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9])
print(temperatures_w1)

[22.5 25.3 20.8 23.4 26.1 24.8 21.9]


2. Inspection and Properties:

In [ ]:
print("Shape:", temperatures_w1.shape)

Shape: (7,)


In [ ]:
print("Data Type:", temperatures_w1.dtype)

Data Type: float64


In [ ]:
print("Number of Elements:", temperatures_w1.size)

Number of Elements: 7


3. Array Operations:

In [ ]:
#Convert the temp from celsius to fahrenheit
# Fahrenheit = (Celsius × 9/5) + 32

temperatures_f = (temperatures_w1 * 9/5) + 32
print("Temperature in Fahrenheit:\n", temperatures_f)

Temperature in Fahrenheit:
 [72.5  77.54 69.44 74.12 78.98 76.64 71.42]


In [ ]:
print("Maximum Temperature:", np.max(temperatures_w1))

Maximum Temperature: 26.1


In [ ]:
print("Minimum Temperature:", np.min(temperatures_w1))

Minimum Temperature: 20.8


In [ ]:
print("Mean Temperature:", np.mean(temperatures_w1))

Mean Temperature: 23.542857142857144


4. Array Slicing and Indexing:

In [ ]:
# Extract the temperatures for the first three days of the week.
first_three_days = temperatures_w1[:3]

print(first_three_days)

[22.5 25.3 20.8]


In [ ]:
# Extract the temperatures for the weekend (last two days).
weekend = temperatures_w1[-2:]

print(weekend)

[24.8 21.9]


In [ ]:
# Extract the temperatures for the middle three days of the week.
middle_three_days = temperatures_w1[2:5]

print(middle_three_days)

[20.8 23.4 26.1]


5. Create a 2D Array:

In [ ]:
temperatures = np.array([
    [22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9],
    [19.2, 22.5, 21.3, 24.0, 23.5, 22.8, 20.1]
])

print(temperatures)

[[22.5 25.3 20.8 23.4 26.1 24.8 21.9]
 [19.2 22.5 21.3 24.  23.5 22.8 20.1]]


6. Inspect and Slice the 2D Array:

In [ ]:
print("Shape:", temperatures.shape)

Shape: (2, 7)


In [ ]:
print("Data Type:", temperatures.dtype)

Data Type: float64


In [ ]:
print("Total Elements:", temperatures.size)

Total Elements: 14


In [ ]:
# Extract the temperatures for each week
week1 = temperatures[0]

print("Week 1:", week1)

Week 1: [22.5 25.3 20.8 23.4 26.1 24.8 21.9]


In [ ]:
week2 = temperatures[1]

print("Week 2:", week2)

Week 2: [19.2 22.5 21.3 24.  23.5 22.8 20.1]


In [ ]:
# Extract the temperatures for weekends (last two days) for both weeks.
week1_weekend = temperatures[0, -2:]

print("Week 1 Weekend:", week1_weekend)

Week 1 Weekend: [24.8 21.9]


In [ ]:
week2_weekend = temperatures[1, -2:]

print("Week 2 Weekend:", week2_weekend)

Week 2 Weekend: [22.8 20.1]


## Pandas Series:

In [ ]:
import pandas as pd

1. Creating Pandas Series:

In [ ]:
marks = pd.Series(
    [95, 92, 89, 85, 80],
    index=['Rank1', 'Rank2', 'Rank3', 'Rank4', 'Rank5']
)

print(marks)

Rank1    95
Rank2    92
Rank3    89
Rank4    85
Rank5    80
dtype: int64


2. Indexing and Slicing:

In [ ]:
# Access the mark of the 1st rank student.
print(marks.iloc[0])

95


In [ ]:
# Use the loc accessor to retrieve the marks of the top 3 ranks by specifying their index labels.
print(marks.loc[['Rank1', 'Rank2', 'Rank3']])

Rank1    95
Rank2    92
Rank3    89
dtype: int64


In [ ]:
# Use the iloc accessor to retrieve the mark of the 3rd-ranked student.
print(marks.iloc[2])

89


In [ ]:
# Retrieve the ranks where the marks are greater than 90.
high_marks = marks[marks > 90]

print(high_marks)

Rank1    95
Rank2    92
dtype: int64


3. Manipulating Series:

In [ ]:
# Modify the mark of the student with the 1st rank to 100.
marks.loc['Rank1'] = 100

print(marks)

Rank1    100
Rank2     92
Rank3     89
Rank4     85
Rank5     80
dtype: int64


In [ ]:
# Remove the entry corresponding to the last rank from the Series.
marks = marks.drop('Rank5')

print(marks)

Rank1    100
Rank2     92
Rank3     89
Rank4     85
dtype: int64


In [ ]:
# Compute the CGPA by dividing each mark in the Series by 10.
cgpa = marks / 10

print(cgpa)

Rank1    10.0
Rank2     9.2
Rank3     8.9
Rank4     8.5
dtype: float64


## Pandas DataFrame:

1. Creating Pandas DataFrame:

In [ ]:
transactions = pd.DataFrame({
    'TransactionID': [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],

    'ProductCategory': [
        'Electronics', 'Clothing', 'Electronics', 'Furniture',
        'Clothing', 'Electronics', 'Furniture', 'Clothing',
        'Furniture', 'Electronics'
    ],

    'Region': [
        'North', 'South', 'North', 'East', 'West',
        'North', 'East', 'West', 'South', 'North'
    ],

    'Amount': [
        200, 150, 300, 450, 200,
        250, 300, 180, 350, 400
    ]
})

print(transactions)

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400


2. Data Exploration:

In [ ]:
print(transactions.head())

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200


In [ ]:
print(transactions.tail())

   TransactionID ProductCategory Region  Amount
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400


In [ ]:
print(transactions.shape)

(10, 4)


In [ ]:
print(transactions.columns)

Index(['TransactionID', 'ProductCategory', 'Region', 'Amount'], dtype='object')


In [ ]:
print(transactions.dtypes)

TransactionID       int64
ProductCategory    object
Region             object
Amount              int64
dtype: object


In [ ]:
# Display only the 'ProductCategory' and 'Amount' columns.

print(transactions[['ProductCategory', 'Amount']])

  ProductCategory  Amount
0     Electronics     200
1        Clothing     150
2     Electronics     300
3       Furniture     450
4        Clothing     200
5     Electronics     250
6       Furniture     300
7        Clothing     180
8       Furniture     350
9     Electronics     400


In [ ]:
# Retrieve the last 3 columns of the DataFrame using iloc or loc.

print(transactions.iloc[:, -3:])

  ProductCategory Region  Amount
0     Electronics  North     200
1        Clothing  South     150
2     Electronics  North     300
3       Furniture   East     450
4        Clothing   West     200
5     Electronics  North     250
6       Furniture   East     300
7        Clothing   West     180
8       Furniture  South     350
9     Electronics  North     400


In [ ]:
# Filter rows where the 'Region' is 'North' and 'Amount' is greater than 200.

filtered_data = transactions[
    (transactions['Region'] == 'North') &
    (transactions['Amount'] > 200)
]

print(filtered_data)

   TransactionID ProductCategory Region  Amount
2            103     Electronics  North     300
5            106     Electronics  North     250
9            110     Electronics  North     400


In [ ]:
# Find the value counts for the 'ProductCategory' column.

print(transactions['ProductCategory'].value_counts())

ProductCategory
Electronics    4
Clothing       3
Furniture      3
Name: count, dtype: int64


In [ ]:
# Find the unique values in the 'Region' column.

print(transactions['Region'].unique())

['North' 'South' 'East' 'West']


In [ ]:
# Group by 'Region' and find the mean amount for each region.

region_mean = transactions.groupby('Region')['Amount'].mean()

print(region_mean)

Region
East     375.0
North    287.5
South    250.0
West     190.0
Name: Amount, dtype: float64


3. Manipulating the DataFrame:

In [ ]:
# Modify the 'Amount' for the transaction with TransactionID 102 to 165.

transactions.loc[
    transactions['TransactionID'] == 102,
    'Amount'
] = 165

print(transactions)

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     165
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400


In [ ]:
# Add a new column 'Discount' by calculating 10% of the 'Amount'.

transactions['Discount'] = transactions['Amount'] * 0.10

print(transactions)

   TransactionID ProductCategory Region  Amount  Discount
0            101     Electronics  North     200      20.0
1            102        Clothing  South     165      16.5
2            103     Electronics  North     300      30.0
3            104       Furniture   East     450      45.0
4            105        Clothing   West     200      20.0
5            106     Electronics  North     250      25.0
6            107       Furniture   East     300      30.0
7            108        Clothing   West     180      18.0
8            109       Furniture  South     350      35.0
9            110     Electronics  North     400      40.0


In [ ]:
# Remove the row with TransactionID 109.

transactions = transactions[
    transactions['TransactionID'] != 109
]

print(transactions)

   TransactionID ProductCategory Region  Amount  Discount
0            101     Electronics  North     200      20.0
1            102        Clothing  South     165      16.5
2            103     Electronics  North     300      30.0
3            104       Furniture   East     450      45.0
4            105        Clothing   West     200      20.0
5            106     Electronics  North     250      25.0
6            107       Furniture   East     300      30.0
7            108        Clothing   West     180      18.0
9            110     Electronics  North     400      40.0


In [ ]:
# Delete the 'Discount' column from the DataFrame.

transactions = transactions.drop(columns=['Discount'])

print(transactions)

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     165
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
9            110     Electronics  North     400
